<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery-1.11.2.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery.flexslider.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery.appear.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery.countTo.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/isotope.pkgd.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/mediaelement-and-player.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery.magnific-popup.min.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/jquery-ui.js"></script>
	<script type="text/javascript" src="{{ asset('/') }}frontend/assets/js/scripts.js"></script>